### ISSUE TITLE
Localizable string

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Customplot#2]
Internationalized texts can be entered in the "package.json" file.
This class does not exist in the PiWeb template file (piweb-*.d.ts).
Can the template file be expanded with it?

**Comment by Schnjan** [comment]
There's no class for localization, the package file is parsed by piweb, while the extension is interpreted by a ClearScript V8 runtime. 

If you want to display localized texts in your plot, you can easily do so, by fetching the current culture like this:

```
piweb.environment.CultureInfo.currentCulture;
```

You can use this information to access a table or a resource file in your extension. Please take note, that you have default javascript functions at your hand, like `JSON.parse()` which can easily parse a translation file into an object.
