### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Customplot#3]
A tooltip can currently only be created at a position. For a rectangle or other geometries is this not possible.

Is it possible in the tooltip to:
  * Format text
  * Add a link to a report page

**Comment by Schnjan** [comment]
Other geometries can be placed with the `drawingContext.placeHighlight` function. Please refer to our plot extension sample report  for examples. 

The content of a tooltip may contain plain text, or templates for certain entities such as characteristics and measurement values. Links are not possible.

**Comment by ThomasFischer1** [comment]
Thanks for the hint.

In the examples MyExtension_1.0.zip or MyExtension_1.1.zip I cannot find any use of a tooltip.
Are there any other examples?

A note on the tooltip page (https://zeiss-piweb.github.io/PiWeb-Plot-Extension/modules/tooltips.html) a reference to "PlaceHighlight" would certainly have been helpful.

**Comment by Schnjan** [comment]
There's a **sample report** with the title **15-Plot-Extensions** that's delievered with PiWeb. You can open all sample reports from the start screen.
