### ISSUE TITLE
Feature: Measure Text

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Customplot#4]
Is there a possibility in the API to calculate the text size, depending on the font etc.?

**Comment by Schnjan** [comment]
Yes, there's a 'measure' method on the FormattedText class. This method is a bit costly. In case it's possible, use the wide range of available arrangement and alignment methods.

[link to documentation](https://zeiss-piweb.github.io/PiWeb-Plot-Extension/classes/drawing.formattedtext.html#measure)
